spring:
  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    
    autenticacao:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    
cors:
  origin: ${CORS_ORIGIN}