spring:
  datasource:
    url: jdbc:mysql://localhost/secretariartc?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    
autenticacao:
  jwt:
    secret: A7%D@XGK=E#fP362c*KD
    expiration: 86400000