spring:
  datasource:
    url: jdbc:${secretariartc}
    username: ${root}
    password: ${root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml